### ISSUE TITLE
Builds fail after update of hisrc-higherjaxb-maven-plugin from 2.1.1 to 2.2.0

### ISSUE THREAD

**Issue by starwarsfan** [patrodyne/hisrc-higherjaxb#6]
All our builds fail if we try to update hisrc-higherjaxb-maven-plugin from 2.1.1 to 2.2.0. Here's the error message:

```bash
[ERROR] Failed to execute goal org.patrodyne.jvnet:hisrc-higherjaxb-maven-plugin:2.2.0:generate (generate-xsd-sources) on project blm: Execution generate-xsd-sources of goal org.patrodyne.jvnet:hisrc-higherjaxb-maven-plugin:2.2.0:generate failed: An API incompatibility was encountered while executing org.patrodyne.jvnet:hisrc-higherjaxb-maven-plugin:2.2.0:generate: java.lang.NoSuchMethodError: 'java.lang.String org.jvnet.basicjaxb.util.LocatorUtils.toLocation(org.xml.sax.Locator)'
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.patrodyne.jvnet:hisrc-higherjaxb-maven-plugin:2.2.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/fooo/.m2/repository/org/patrodyne/jvnet/hisrc-higherjaxb-maven-plugin/2.2.0/hisrc-higherjaxb-maven-plugin-2.2.0.jar
[ERROR] urls[1] = file:/home/fooo/.m2/repository/org/patrodyne/jvnet/hisrc-higherjaxb-maven-plugin-core/2.2.0/hisrc-higherjaxb-maven-plugin-core-2.2.0.jar
[ERROR] urls[2] = file:/home/fooo/.m2/repository/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0.jar
[ERROR] urls[3] = file:/home/fooo/.m2/repository/com/sun/org/apache/xml/internal/resolver/20050927/resolver-20050927.jar
[ERROR] urls[4] = file:/home/fooo/.m2/repository/org/sonatype/plexus/plexus-build-api/0.0.7/plexus-build-api-0.0.7.jar
[ERROR] urls[5] = file:/home/fooo/.m2/repository/org/codehaus/plexus/plexus-utils/4.0.0/plexus-utils-4.0.0.jar
[ERROR] urls[6] = file:/home/fooo/.m2/repository/org/apache/maven/plugin-tools/maven-plugin-annotations/3.11.0/maven-plugin-annotations-3.11.0.jar
[ERROR] urls[7] = file:/home/fooo/.m2/repository/org/patrodyne/jvnet/hisrc-higherjaxb40-maven-plugin/2.2.0/hisrc-higherjaxb40-maven-plugin-2.2.0.jar
[ERROR] urls[8] = file:/home/fooo/.m2/repository/jakarta/activation/jakarta.activation-api/2.1.2/jakarta.activation-api-2.1.2.jar
[ERROR] urls[9] = file:/home/fooo/.m2/repository/jakarta/annotation/jakarta.annotation-api/2.1.1/jakarta.annotation-api-2.1.1.jar
[ERROR] urls[10] = file:/home/fooo/.m2/repository/jakarta/xml/bind/jakarta.xml.bind-api/4.0.1/jakarta.xml.bind-api-4.0.1.jar
[ERROR] urls[11] = file:/home/fooo/.m2/repository/org/glassfish/jaxb/codemodel/4.0.4/codemodel-4.0.4.jar
[ERROR] urls[12] = file:/home/fooo/.m2/repository/org/glassfish/jaxb/jaxb-runtime/4.0.4/jaxb-runtime-4.0.4.jar
[ERROR] urls[13] = file:/home/fooo/.m2/repository/org/glassfish/jaxb/jaxb-core/4.0.4/jaxb-core-4.0.4.jar
[ERROR] urls[14] = file:/home/fooo/.m2/repository/org/eclipse/angus/angus-activation/2.0.1/angus-activation-2.0.1.jar
[ERROR] urls[15] = file:/home/fooo/.m2/repository/org/glassfish/jaxb/txw2/4.0.4/txw2-4.0.4.jar
[ERROR] urls[16] = file:/home/fooo/.m2/repository/com/sun/istack/istack-commons-runtime/4.1.2/istack-commons-runtime-4.1.2.jar
[ERROR] urls[17] = file:/home/fooo/.m2/repository/org/glassfish/jaxb/jaxb-xjc/4.0.4/jaxb-xjc-4.0.4.jar
[ERROR] urls[18] = file:/home/fooo/.m2/repository/org/glassfish/jaxb/xsom/4.0.4/xsom-4.0.4.jar
[ERROR] urls[19] = file:/home/fooo/.m2/repository/com/sun/xml/bind/external/relaxng-datatype/4.0.4/relaxng-datatype-4.0.4.jar
[ERROR] urls[20] = file:/home/fooo/.m2/repository/com/sun/xml/bind/external/rngom/4.0.4/rngom-4.0.4.jar
[ERROR] urls[21] = file:/home/fooo/.m2/repository/com/sun/xml/dtd-parser/dtd-parser/1.5.1/dtd-parser-1.5.1.jar
[ERROR] urls[22] = file:/home/fooo/.m2/repository/com/sun/istack/istack-commons-tools/4.1.2/istack-commons-tools-4.1.2.jar
[ERROR] urls[23] = file:/home/fooo/.m2/repository/org/slf4j/jcl-over-slf4j/2.0.9/jcl-over-slf4j-2.0.9.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
```

Is there anything else to update? I've already tried to update hisrc-hyperjaxb-annox-plugin to 2.2.0 too but that makes no difference. Any ideas?

```bash
Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546)
Java version: 21.0.1, vendor: Private Build, runtime: /usr/lib/jvm/java-21-openjdk-amd64
```

**Comment by starwarsfan** [comment]
Never mind, seems I run into a chain of different problems. Figured out that a different Maven version (3.8) was used during the build than my manual Maven version check. After I pinned the build to Maven 3.9, everything works as expected again.

Thx for your work!
